import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { StyledEngineProvider } from '@mui/material'
import { ThemeProvider } from '@/components/theme-provider'
import clsx from 'clsx'
import { ReactNode } from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

interface Props {
  children: ReactNode
}

const Layout = ({ children }: Props) => {
  return (
    <html lang='zh_CN'>
      <body className={clsx([inter.className, 'h-screen'])}>
        <StyledEngineProvider injectFirst>
          <ThemeProvider>
            {/* 页面 */}
            {children}
          </ThemeProvider>
        </StyledEngineProvider>
      </body>
    </html>
  )
}

export default Layout
